#!/bin/sh

#SBATCH --job-name=ds003752-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003752-fmriprep/.reproman/jobs/local/20230824-194824-4ba1/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003752-fmriprep/.reproman/jobs/local/20230824-194824-4ba1/stderr

#SBATCH --nodes=1
#SBATCH --ntasks=3
#SBATCH --time=48:00:00
#SBATCH --partition=small

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003752-fmriprep/.reproman/jobs/local/20230824-194824-4ba1

module load launcher
module load remora
module load ooops
set_io_param_batch $SLURM_JOBID 0 low
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 2); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

# Symlink containers annex to node tmp
chmod -R 775 code/containers/.git/annex
rm -rf code/containers/.git/annex
ln -s /tmp/annexes/containers code/containers/.git/annex

# Use cdtools to copy containers to node tmp
CDTools=/home1/apps/CDTools/1.1
export PATH=${PATH}:${CDTools}/bin
distribute.bash ${STAGING}/annexes

wait

remora "$LAUNCHER_DIR"/paramrun